#include <stdio.h>
#include "lcdManager.h"

// Estados de las casillas del tablero
#define CASILLA_VACIA 0
#define FICHA_BLANCA  1
#define FICHA_NEGRA   2


#define DIM   8

char __attribute__ ((aligned (8))) tablero[DIM][DIM] = {
        {FICHA_NEGRA, FICHA_BLANCA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA},
        {CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA},
        {CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA},
        {CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, FICHA_NEGRA, FICHA_BLANCA, CASILLA_VACIA, CASILLA_VACIA},
        {CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, FICHA_BLANCA, FICHA_NEGRA, CASILLA_VACIA, CASILLA_VACIA},
        {CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA},
        {CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA},
        {CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, CASILLA_VACIA, FICHA_NEGRA}
};

int main() {
    printf("Dibujando\n");
    LcdM_Show_Skip();
    return 0;
}